"""Run first migration

Revision ID: 578f1dae4e22
Revises: 
Create Date: 2018-09-10 13:33:39.967875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578f1dae4e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrier', sa.String(length=6), nullable=True),
    sa.Column('carrier_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier', 'carrier_name', name='uix_1')
    )
    op.create_table('airport',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('city_name', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=6), nullable=True),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bts_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=True),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('departures', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.id'], ),
    sa.ForeignKeyConstraint(['dest_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bts_record')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
