"""trial

Revision ID: 98fa87a81714
Revises: 
Create Date: 2018-08-18 10:22:16.971671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fa87a81714'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departures_scheduled', sa.Integer(), nullable=True),
    sa.Column('departures_performed', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('freight', sa.Integer(), nullable=True),
    sa.Column('mail', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('ramp_to_ramp', sa.Integer(), nullable=True),
    sa.Column('air_time', sa.Integer(), nullable=True),
    sa.Column('unique_carrier', sa.String(length=6), nullable=True),
    sa.Column('airline_id', sa.Integer(), nullable=True),
    sa.Column('unique_carrier_name', sa.String(length=128), nullable=True),
    sa.Column('unique_carrier_entity', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=3), nullable=True),
    sa.Column('carrier', sa.String(length=6), nullable=True),
    sa.Column('carrier_name', sa.String(length=128), nullable=True),
    sa.Column('carrier_group', sa.String(length=3), nullable=True),
    sa.Column('carrier_group_new', sa.String(length=3), nullable=True),
    sa.Column('origin_airport_id', sa.Integer(), nullable=True),
    sa.Column('origin_airport_seq_id', sa.Integer(), nullable=True),
    sa.Column('origin_city_market_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=6), nullable=True),
    sa.Column('origin_city_name', sa.String(length=64), nullable=True),
    sa.Column('origin_country', sa.String(length=6), nullable=True),
    sa.Column('origin_country_name', sa.String(length=64), nullable=True),
    sa.Column('origin_wac', sa.Integer(), nullable=True),
    sa.Column('dest_airport_id', sa.Integer(), nullable=True),
    sa.Column('dest_airport_seq_id', sa.Integer(), nullable=True),
    sa.Column('dest_city_market_id', sa.Integer(), nullable=True),
    sa.Column('dest', sa.String(length=6), nullable=True),
    sa.Column('dest_city_name', sa.String(length=64), nullable=True),
    sa.Column('dest_country', sa.String(length=6), nullable=True),
    sa.Column('dest_country_name', sa.String(length=64), nullable=True),
    sa.Column('dest_wac', sa.Integer(), nullable=True),
    sa.Column('aircraft_group', sa.Integer(), nullable=True),
    sa.Column('aircraft_type', sa.Integer(), nullable=True),
    sa.Column('aircraft_config', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('distance_group', sa.Integer(), nullable=True),
    sa.Column('CLASS', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('record')
    # ### end Alembic commands ###
