"""empty message

Revision ID: a9ccaca4ea79
Revises: 578f1dae4e22
Create Date: 2018-09-13 15:35:59.827555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ccaca4ea79'
down_revision = '578f1dae4e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airportgeo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(), nullable=True),
    sa.Column('lng', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('airportgeo')
    # ### end Alembic commands ###
